### ISSUE TITLE
Revocation

### ISSUE THREAD

**Issue by bernie-g** [IhsotasOtomakan/lol-backend-openid#1]
Thank you for compiling all this information in one repo! I was looking through the OIDC and saw that there was an endpoint for revoking a token: https://auth.riotgames.com/token/revoke
I can't seem to figure out how to use it though, when I try to post to it it says it requires a client_id and an authentication type. Do you have any idea how it works? @IhsotasOtomakan 

Thanks!

**Comment by 5z3f** [comment]
Proper request looks like this:

```
POST auth.riotgames.com/token/revoke HTTP/1.1
user-agent: RiotClient/18.3.0 (lol-rso-auth)
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
X-Riot-DSID: {UUID v4 without dash}
Accept: application/json
Content-Length: {Request body length}

client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer&
client_assertion={token}&
grant_type=password&
token={ec1:{refreshToken}}&
token_type_hint=refresh_token
```
Authentication API revamp is coming and will hit live servers very soon, if I will have enough free time I'm gonna document it in a new repository

**Comment by bernie-g** [comment]
> 
> 
> Proper request looks like this:
> 
> ```
> POST auth.riotgames.com/token/revoke HTTP/1.1
> user-agent: RiotClient/18.3.0 (lol-rso-auth)
> Cache-Control: no-cache
> Content-Type: application/x-www-form-urlencoded
> X-Riot-DSID: {UUID v4 without dash}
> Accept: application/json
> Content-Length: {Request body length}
> 
> client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer&
> client_assertion={token}&
> grant_type=password&
> token={ec1:{refreshToken}}&
> token_type_hint=refresh_token
> ```
> 
> Authentication API revamp is coming and will hit live servers very soon, if I will have enough free time I'm gonna document it in a new repository

Thank you very much, I appreciate it!
